language: go
go:
  - 1.10
  - 1.11
install:
  - go get github.com/Sirupsen/logrus
  - go get github.com/satori/go.uuid
  - go get github.com/stretchr/testify
  - go get github.com/mattn/goveralls
script:
  - go test -covermode=count -coverprofile=coverage.out -v github.com/ronelliott/go-events
after_success:
  - goveralls -service travis-ci -covermode=count -coverprofile=coverage.out -repotoken=$COVERALLS_REPO_TOKEN
