language: go
go:
  - 1.10
install:
  - go get github.com/Masterminds/glide
  - (cd src/github.com/ronelliott/go-events && ../../../../bin/glade install)
  - go get github.com/mattn/goveralls
script:
  - go test -covermode=count -coverprofile=coverage.out -v github.com/ronelliott/go-events
after_success:
  - goveralls -service travis-ci -covermode=count -coverprofile=coverage.out -repotoken=$COVERALLS_REPO_TOKEN
